site_name: Docksal Documentation
theme: readthedocs
repo_url: https://github.com/docksal/docksal
extra_css:
  - css/extra.css
pages:
  - Home: index.md
  - Getting started:
    - System requirements: system-requirements.md
    - Docksal environment setup: env-setup.md
    - Configure a project to use Docksal: project-setup.md
  - Advanced configuration:
    - Drupal settings: drupal-settings.md
    - Overriding default PHP/MySQL/etc. settings: settings.md
    - MySQL DB access for external tools: db-access.md
    - Automatic database import: db-import.md
    - Extending fin with custom commands: custom-commands.md
  - Third party utililies:
    - Debugging with Xdebug and PhpStorm: xdebug.md
    - Using PHP Code Sniffer (phpcs, phpcbf): phpcs.md
    - Using Blackfire profiler: blackfire.md
    - Public access via ngrok: public-access.md
    - Using Behat: behat.md
    - Sending and capturing e-mail: mail.md
    - Enabling Varnish support: varnish.md
    - Enabling Apache Solr support: apache-solr.md
    - Using Sass: sass.md
    - Using custom ssh keys (with or without passwords) via ssh-agent: ssh-agent.md
