site_name: Docksal Documentation
theme: readthedocs
theme_dir: docs/_custom_theme
repo_url: https://github.com/docksal/docksal
site_url: https://docs.docksal.io
extra_css:
  - _css/extra.css
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Home: index.md
  - Getting started:
    - What's in the software?: getting-started/the-software.md
    - Setup instructions: getting-started/setup.md
    - System requirements: getting-started/system-requirements.md
    - Docksal setup: getting-started/env-setup.md
    - Project setup: getting-started/project-setup.md
    - Docker for Mac/Windows: getting-started/env-setup-native.md
    - Upgrading from Drude (DDE): getting-started/upgrade-dde.md
    - Portable installation: getting-started/portable.md
  - Troubleshooting:
    - General: troubleshooting.md
    - Windows SMB shares: troubleshooting-smb.md
  - Docksal Fin:
    - fin: fin/fin.md
    - Custom commands: fin/custom-commands.md
    - Addons: fin/addons.md
    - Folder aliases: fin/aliases.md
  - Tools and integrations:
    - Apache Solr: tools/apache-solr.md
    - Acquia Drush Commands: tools/acquia-drush.md
    - Behat: tools/behat.md
    - Blackfire: tools/blackfire.md
    - Drupal Console: tools/drupal-console.md
    - Drush: tools/drush.md
    - MailHog: tools/mailhog.md
    - Memcached: tools/memcached.md
    - ngrok: tools/ngrok.md
    - PHP Code Sniffer: tools/phpcs.md
    - SASS and Compass: tools/sass.md
    - Terminus: tools/terminus.md
    - Varnish: tools/varnish.md
    - Xdebug: tools/xdebug.md
  - Advanced configuration:
    - Stack configuration:
      - Stack: advanced/stack.md
      - Stack configuration: advanced/stack-config.md
      - PHP/MySQL/etc. settings: advanced/stack-settings.md
      - Drupal settings: advanced/drupal-settings.md
      - Multiple projects/domains: advanced/multiple-projects.md
      - VM resources: advanced/vm.md
      - Networking: advanced/networking.md
      - DNS resolver: advanced/dns-resolver.md
      - Extending stock images: advanced/extend-images.md
    - SSH agent: advanced/ssh-agent.md
    - Database:
      - Database access: advanced/db-access.md
      - Automatic database import: advanced/db-import.md
      - Database sandbox mode: advanced/db-sandbox.md
    - Web Server:
      - HTTP Basic Authentication: advanced/web-http-auth.md
      - Web server logs: advanced/web-logs.md
      - Configuration overrides: advanced/web-configuration-overrides.md
    - File sharing: advanced/file-sharing.md
    - Docker volumes: advanced/volumes.md
    - Stats and analytics: advanced/analytics.md
