site_name: Docksal Documentation
theme: readthedocs
repo_url: https://github.com/docksal/docksal
extra_css:
  - css/extra.css
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Home: index.md
  - Getting started:
    - System requirements: system-requirements.md
    - Docksal environment setup: env-setup.md
    - Configure a project to use Docksal: project-setup.md
  - Advanced configuration:
    - Running multiple projects: multiple-projects.md
    - Drupal settings (database, files): drupal-settings.md
    - Overriding default PHP/MySQL/etc. settings: settings.md
    - MySQL DB access for external tools: db-access.md
    - Automatic database import: db-import.md
    - Extending fin with custom commands: custom-commands.md
    - Exposing any Docker containers port: expose-port.md
    - Using Docker for Mac/Win: env-setup-native.md
    - Customize project configuration: project-customize.md
  - Utililies:
    - Debugging with Xdebug and PhpStorm: xdebug.md
    - Using custom ssh keys (with or without passwords) via ssh-agent: ssh-agent.md
    - Sending and capturing e-mail: mail.md
    - SASS and Compass: sass.md
    - PHP Code Sniffer (phpcs, phpcbf): phpcs.md
    - Varnish: varnish.md
    - Memcached: memcached.md
    - Apache Solr: apache-solr.md
    - Blackfire profiler: blackfire.md
    - Behat: behat.md
    - Public access via ngrok: public-access.md
