#!/usr/bin/env bash

## Run Code Sniffer (phpcs) against given path
##
## Usage: fin phpcs <path>
##
## Uses WordPress standards.
##
# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

if [[ "$1" == "" ]]; then
	echo "Usage: fin phpcs <path>"
	exit 1
fi

fin run phpcs \
	--standard="WordPress" -n \
	"$1"
