#!/usr/bin/env bash

## Run Code Sniffer (phpcs) against given path
##
## Usage: dsh phpcs <path>
##
## Uses Drupal standards.
##
## Includes extensions:	php, module, inc, install, test, profile, theme
## Ignores:		features.*, *.pages*.inc

# Environment variables passed from dsh:
#
#   $DRUDE_PATH - (string) absolute path to NEAREST .drude folder
#   $YML_PATH - (string) absolute path to NEAREST docker-compose.yml, can be empty
#   $DOCKER_RUNNING - (string) "true" or "false"

if [[ "$1" == "" ]]; then
	echo "Usage: dsh phpcs <path>"
	exit 1
fi

dsh run phpcs \
	--standard=Drupal -n \
	--extensions="php,module,inc,install,test,profile,theme" \
	--ignore="*.features.*,*.pages*.inc" \
	"$1"
