# Acquia alike stack
#
# - Apache 2.4
# - MySQL 5.6
# - PHP 5.6 / PHP 7.0
# - Varnish 4
# - Memcached 1.4
# - ApacheSolr 4.x

version: "2.1"

services:
  # Web
  web:
    hostname: web
    image: docksal/web:2.1-apache2.4
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
      - APACHE_BASIC_AUTH_USER
      - APACHE_BASIC_AUTH_PASS
    depends_on:
      - cli
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # DB
  db:
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # CLI
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: docksal/cli:1.3-php7
    volumes:
      # Project root volume
      - project_root:/var/www:rw,nocopy
      # Shared ssh-agent socket
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
      - HOST_UID
      - HOST_GID
      - DOCROOT
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
      # Point xdebug to the host IP
      - XDEBUG_CONFIG=remote_connect_back=0 remote_host=${DOCKSAL_HOST_IP}
      # This helps with console scripts debugging in PHPStorm
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Varnish
  varnish:
    hostname: varnish
    image: docksal/varnish:3.0-stable
    labels:
      - io.docksal.virtual-host=varnish.${VIRTUAL_HOST}
    environment:
      - VARNISH_BACKEND_HOST=web
    depends_on:
      - web
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Memcached
  memcached:
    hostname: memcached
    image: ${MEMCACHED_IMAGE:-memcached:1.4-alpine}
    # Set memcached memory limit to 128 MB by default
    command: ["-m", "128"]
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # Solr
  solr:
    hostname: solr
    image: docksal/solr:4.x-stable
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
