# Acquia alike stack
#
# - Apache 2.4
# - MariaDB 10.4 (MySQL 5.7 drop-in replacement)
# - PHP 8.1
# - Varnish 6.6
# - Memcached 1.6
# - Apache Solr 7

version: "3.9"

services:
  # http(s)://VIRTUAL_HOST
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: apache
    depends_on:
      - cli

  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mariadb
    # Pin MariaDB version
    # MariaDB v10.4 functions as limited drop-in replacement for MySQL 5.7
    image: ${DB_IMAGE:-docksal/mariadb:10.4-1.3}

  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    # Pin PHP version
    image: ${CLI_IMAGE:-docksal/cli:php8.1-3.3}

  # http(s)://varnish.VIRTUAL_HOST
  varnish:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish
    # Pin Varnish version
    image: ${VARNISH_IMAGE:-docksal/varnish:6.6-3.1}
    depends_on:
      - web

  memcached:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: memcached
    # Pin Memcached version
    image: ${MEMCACHED_IMAGE:-memcached:1.6-alpine}

  # http(s)://solr.VIRTUAL_HOST/solr
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    # Pin Solr version
    image: ${SOLR_IMAGE:-docksal/solr:7}
