# Pantheon alike stack
#
# - Nginx 1.14
# - MariaDB 10.4
# - PHP 7.2
# - Varnish 4.1
# - Redis 4.0
# - ApacheSolr 3.6

version: "3.9"

services:
  # http(s)://VIRTUAL_HOST
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: nginx
    # Pin nginx version
    image: ${WEB_IMAGE:-docksal/nginx:1.14-edge}
    depends_on:
      - cli

  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mariadb
    # Pantheon supports 10.4
    image: ${WEB_IMAGE:-docksal/mariadb:10.4}

  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli

  # http(s)://varnish.VIRTUAL_HOST
  varnish:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish
    # Pin Varnish version
    image: ${VARNISH_IMAGE:-docksal/varnish:4.1-2.0}
    depends_on:
      - web

  redis:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: redis
    # Pin Redis version
    image: ${REDIS_IMAGE:-wodby/redis:6.2}

  # http(s)://solr.VIRTUAL_HOST/solr
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    # Pin Solr version
    image: ${SOLR_IMAGE:-docksal/solr:1.0-solr3}
