# Platform.sh alike stack
# see https://github.com/platformsh-templates/drupal9
#
# - Nginx 1.20
# - MariaDB 10.4 (MySQL 5.7 drop-in replacement)
# - PHP 8.1
# - Redis 5.0

services:
  # http(s)://VIRTUAL_HOST
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: nginx
    # Pin nginx version
    image: ${WEB_IMAGE:-docksal/nginx:1.20-1.2}
    depends_on:
      - cli

  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mariadb
    # Pin MariaDB version
    # MariaDB v10.4 functions as limited drop-in replacement for MySQL 5.7
    image: ${DB_IMAGE:-docksal/mariadb:10.4-1.4}

  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    # Pin PHP version
    image: ${CLI_IMAGE:-docksal/cli:php8.1-3.8}

  redis:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: redis
    # Pin Redis version
    image: ${REDIS_IMAGE:-wodby/redis:5.0}
