# Sync project volumes with Unison
# For use with Docker for Mac osxfs.
# Pros: native fs performance, fast file sync, inotify/fs watchers support.
# Cons: 2x space usage (a mirror of the code base is maintained in a Docker volume), initial sync delay

version: "2.1"

volumes:
  project_root:

  # Bind mount host_home
  host_home:
    driver: local
    driver_opts:
      type: none
      # $HOST_HOME is a cross-platform version of $HOME. It is exported by fin.
      # It returns a Unix style path on Windows (which is what we need here), while $HOME return a Windows style path.
      device: ${HOST_HOME}
      o: bind

services:
  # Sync project_root volume from host with unison 
  bg-sync:
    image: cweagans/bg-sync
    volumes:
      - "${PROJECT_ROOT}:/source"
      - project_root:/destination
    environment:
      - SYNC_DESTINATION=/destination
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true

  # Shared ssh-agent volume
  docksal_ssh_agent:
    external: true
