#!/usr/bin/env bash

# Used to trigger TravisCI builds for the dependent repos
#
# Usage: travisci-build-trigger repo-name
#
# Example: travisci-build-trigger docksal/drupal8

# Read repo name from the first argument and replace / with %2F
# The %2F in the request URL is required so that the owner and repository name in the repository slug are interpreted
# as a single URL segment.
REPO=${1/\//%2F}

# Read branch from the second argument. Use "master" by default
BRANCH=${2:-master}

body='{
"request": {
"branch":"'${BRANCH}'"
}}'

curl -s -X POST \
	-H "Content-Type: application/json" \
	-H "Accept: application/json" \
	-H "Travis-API-Version: 3" \
	-H "Authorization: token $TRAVIS_API_TOKEN" \
	-d "$body" \
	https://api.travis-ci.org/repo/${REPO}/requests
